### ISSUE TITLE
Can't get Image Processing Examples Working (ch6/interp_image.py)

### ISSUE THREAD

**Issue by gboutet** [oysstu/pyopencl-in-action#1]
Hello, 
I'm willing to do some image interpolation with PyOpenCL, so I tried to run your example but I got the following error : 

input.cl:2:32: error: use of undeclared identifier 'CLK_NORMALIZED_COORDS_FALSE'
input.cl:2:62: error: use of undeclared identifier 'CLK_ADDRESS_CLAMP'
input.cl:2:82: error: use of undeclared identifier 'CLK_FILTER_LINEAR'
input.cl:22:18: error: implicit declaration of function 'read_imagef' is invalid in C99
input.cl:26:10: error: implicit declaration of function 'write_imagef' is invalid in C99
input.cl:26:10: note: did you mean 'read_imagef'?
input.cl:22:18: note: 'read_imagef' declared here

I also get this kind of error while running simple_image.py
However I am able to run other examples that you provided on this repository, so I don't understand where these errors come from. 

Any Idea of what is going wrong ? 

Guillaume

**Comment by oysstu** [comment]
Are you running OpenCL on your CPU? Some of the examples require a GPU if I remember correctly.

**Comment by gboutet** [comment]
No I'm running it on my AMD GPUs (Radeon HD 7600G or Radeon HD 8730M)

**Comment by oysstu** [comment]
Strange, it works fine on my nvidia card. Perhaps there is a more recent OpenCL version you can try? My guess is that it's a case of missing support for these image operations.

**Comment by gboutet** [comment]
Well I don't think the problem comes from the openCL version, my Graphic card is running OpenCL 1.1 , I've checked the docs for this version, and both read_imagef / write_imagef and the CLK_CONSTANTS are available ( see https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/)

**Comment by oysstu** [comment]
That does not mean that AMD has implemented support for these features for that version. I did not mean the opencl version, but the AMD driver. At any rate, I cannot help you with this issue unfortunately. I suggest you either take it to the pyopencl developers or search around for anyone having the same issue.

One last thing to try is to change the uint16 image to uint8, perhaps there is no support for non-standard images.

**Comment by gboutet** [comment]
Ok thanks anyway  !

**Comment by oysstu** [comment]
Feel free to add a comment if you find a solution or reason
