### ISSUE TITLE
import utility

### ISSUE THREAD

**Issue by ghost** [oysstu/pyopencl-in-action#3]
I have trouble to `import utility` from the root of the project due to this 
I have modified and added `sys.path.append("..")`  for myself _ch3/map_copy.py_  

```
'''
Listing 3.3: Copying and mapping buffer objects
'''

import sys
sys.path.append("..")

import pyopencl as cl
import numpy as np
import utility
```

as well I have modified project structure
 
```
    pyopencl-in-action\
        __init__.py
        utility.py
        ch3\
            __init__.py
            map_copy.py
            buffer_test.py
        ch4\
            __init__.py
            float_config.py
            double_test.py
```

at least on my side without those modification I run into

```
(cl) ~/work/pyopencl-in-action/ch3$ python buffer_test.py 
Traceback (most recent call last):
  File "buffer_test.py", line 7, in <module>
    import utility
ModuleNotFoundError: No module named 'utility'

```

due to compatibility with python2 I added into _`opencl-print-info.py`_

`from __future__ import print_function`

**Comment by oysstu** [comment]
The imports are relative to the root directory, and must be run as a module from the top dir.
`python3 -m "ch3.buffer_test"`

**Comment by ghost** [comment]
true for python3 but python2?

**Comment by oysstu** [comment]
If I remember correctly, you should be able to do the following in python 2
`from ..utility import function`

**Comment by ghost** [comment]
Yeah - but ..
 
```
    from ..utility import *
ValueError: Attempted relative import in non-package

```
